apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  namespace: microservices
type: Opaque
stringData:
  ConnectionStrings__Default: >
    Server=sql-payments,1433;
    Database=PaymentsDb;
    User Id=sa;
    Password=StrongPassword!123;
    TrustServerCertificate=True;