apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  namespace: microservices
  labels:
    app: payments-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"