apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentsapi
  template:
    metadata:
      labels:
        app: paymentsapi
    spec:
      containers:
        - name: paymentsapi
          image: paymentsapi:fixed2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            # Variáveis do ConfigMap
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: paymentsapi-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_QUEUE_PAYMENT_CREATED
              valueFrom:
                configMapKeyRef:
                  name: paymentsapi-config
                  key: RABBITMQ_QUEUE_PAYMENT_CREATED
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: paymentsapi-config
                  key: RABBITMQ_VHOST
            # Variáveis do Secret
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: paymentsapi-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymentsapi-secret
                  key: RABBITMQ_PASSWORD
            - name: ConnectionStrings__PaymentsDb
              valueFrom:
                secretKeyRef:
                  name: paymentsapi-secret
                  key: ConnectionStrings__Default
