apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentsapi
  template:
    metadata:
      labels:
        app: paymentsapi
    spec:
      containers:
        - name: paymentsapi
          image: paymentsapi:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: paymentsapi-config
            - secretRef:
                name: paymentsapi-secret
