apiVersion: v1
kind: Secret
metadata:
  name: paymentsapi-secret
type: Opaque
stringData:
  ConnectionStrings__Default: >
    Server=sql-payments,1433;
    Database=PaymentsDb;
    User Id=sa;
    Password=StrongPassword!123;
    TrustServerCertificate=True;
  RABBITMQ_USERNAME: fiap
  RABBITMQ_PASSWORD: fiap123