apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-payments
  template:
    metadata:
      labels:
        app: sql-payments
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-payments-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: sql-data
          emptyDir: {}
